conn:
  server: '127.0.0.1:57314'
  cert: ''
  timeout:
    dial: 5s
    file: 1m
throughput:
  concurrency: 8
  chunk: 32768
  delay: 0s
files:
  patterns:
    - '/tmp/perf/*'
#  processed: '/tmp/processed/'
  delete: true
  gatekeeper: true
response:
  report: 5s
delta: 5s
staging: '/tmp/staging/'
