name: "Nightly Build"
on:
  schedule:
    - cron: '0 2 * * *'
jobs:
  strelka:
    name: "Strelka Nightly Build"
    env:
        DOCKER_BUILDKIT: 1
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Builds Strelka
        run: docker compose -f build/docker-compose.yaml build
