---
name: Style Automation
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black mypy flake8 isort

      - name: Code quality checks
        run: |
          python -m black --extend-exclude .*_pb2.*\.py --check --diff src/python
          python -m flake8 --exclude src/python/build/,src/python/strelka/proto/ src/python
          python -m isort --extend-skip-glob *_pb2*.py --profile black --check-only src/python
